apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: angular1.example.com
   http:
     paths:
     - path: /
       backend:
         serviceName: anjenkins8
         servicePort: 80